language: ruby
sudo: false
env:
  - RACK_ENV=test
before_script: bundle exec rake ar:create && bundle exec rake ar:migrate
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - sudo apt-get install sqlite3
  - gem update bundler

matrix:
  allow_failures:
    - rvm: 2.5

  include:
    - rvm: 1.9.3
      gemfile: gemfiles/ruby-1.9.3

notifications:
  email: false
