language: ruby
sudo: false
env:
  - RACK_ENV=test
before_script: bundle exec rake ar:create && bundle exec rake ar:migrate
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update bundler

matrix:
  allow_failures:
    - rvm: 2.5

notifications:
  email: false
