language: ruby
sudo: false
env:
  - RACK_ENV=test
before_script: bundle exec rake ar:create && bundle exec rake ar:migrate
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

before_install:
  - gem update bundler

notifications:
  email: false
