version: "0.2.0b{build}"

environment:
  matrix:
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 200-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - set PATH=C:\MinGW\bin;%PATH%
  - set RAKEOPT=-rdevkit
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
